

#8mm
image_width: 1440
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [2418.16555,    0.     ,  727.51149,
            0.     , 2411.728  ,  525.63697,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.025997, 0.106359, -0.000702, -0.001103, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [2413.51685,    0.     ,  726.17575,    0.     ,
            0.     , 2407.47046,  524.78654,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
















#6mm

      


# image_width: 1440
# image_height: 1080
# camera_name: narrow_stereo
# camera_matrix:
#   rows: 3
#   cols: 3
#   data: [1815.35593,    0.     ,  757.44026,
#             0.     , 1812.54923,  540.84684,
#             0.     ,    0.     ,    1.     ]
# distortion_model: plumb_bob
# distortion_coefficients:
#   rows: 1
#   cols: 5
#   data: [-0.070270, -0.004536, -0.000523, -0.000291, 0.000000]
# rectification_matrix:
#   rows: 3
#   cols: 3
#   data: [1., 0., 0.,
#          0., 1., 0.,
#          0., 0., 1.]
# projection_matrix:
#   rows: 3
#   cols: 4
#   data: [1794.52272,    0.     ,  758.08426,    0.     ,
#             0.     , 1801.02279,  540.60538,    0.     ,
#             0.     ,    0.     ,    1.     ,    0.     ]