

#8mm
# image_width: 1440
# image_height: 1080
# camera_name: narrow_stereo
# camera_matrix:
#   rows: 3
#   cols: 3
#   data: [2418.16555,    0.     ,  727.51149,
#             0.     , 2411.728  ,  525.63697,
#             0.     ,    0.     ,    1.     ]
# distortion_model: plumb_bob
# distortion_coefficients:
#   rows: 1
#   cols: 5
#   data: [-0.025997, 0.106359, -0.000702, -0.001103, 0.000000]
# rectification_matrix:
#   rows: 3
#   cols: 3
#   data: [1., 0., 0.,
#          0., 1., 0.,
#          0., 0., 1.]
# projection_matrix:
#   rows: 3
#   cols: 4
#   data: [2413.51685,    0.     ,  726.17575,    0.     ,
#             0.     , 2407.47046,  524.78654,    0.     ,
#             0.     ,    0.     ,    1.     ,    0.     ]
















#6mm

      


image_width: 1440
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1809.59745,    0.     ,  714.912  ,
            0.     , 1806.07962,  562.07534,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.087036, 0.102188, -0.000668, -0.000807, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1787.67859,    0.     ,  713.60175,    0.     ,
            0.     , 1791.71765,  561.50231,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]