use_calculation: false

debug:
  debug_mode: true
  debug_w: 1440
  debug_h: 1080
  debug_show_dt: 0.1

max_infer_running: 4

classify_model_path: "/home/hy/wust_vision/model/lenet.onnx"
classify_label_path: "/home/hy/wust_vision/model/label.txt"


model:
  model_path: "/home/hy/wust_vision/model/opt-1208-001.onnx"
  device_type: "GPU"  
  conf_threshold: 0.25
  top_k: 128
  nms_threshold: 0.3


light:
  expand_ratio_w: 1.1
  expand_ratio_h: 1.1
  binary_thres: 85
  min_ratio: 0.02
  max_ratio: 0.45
  max_angle: 40.0


camera:
  camera_info_path: "/home/hy/wust_vision/config/camera_info.yaml"
  serial: "" 
  acquisition_frame_rate: 160
  exposure_time: 2500
  gain: 12.0
  adc_bit_depth: "Bits_8"
  pixel_format: "BayerRG8"

detect_color: 0

tracker:
  target_frame: "odom"
  max_match_distance: 0.5
  max_match_yaw_diff: 0.7
  tracking_thres: 5
  lost_time_thres: 0.2
  ekf:
    s2qx: 10.0
    s2qy: 10.0
    s2qz: 1.0
    s2qyaw: 20.0
    s2qr: 80.0
    s2qd_zc: 800.0
    r_x: 0.0043715573
    r_y: 0.0443530405
    r_z: 0.0536129460
    r_yaw: 0.1651087658
solver:
      prediction_delay: 0.0
      controller_delay: 0.0
      max_tracking_v_yaw: 180.0 #转速(rad/s)大于这个值时瞄准机器人中心 
      side_angle: 20.0 
      bullet_speed: 25.0
      compenstator_type: "ideal"
      gravity: 9.8
      resistance: 0.092
      iteration_times: 120 # 补偿的迭代次数
      # ["距离下限, 距离上限, 高度下限, 高度下限, pitch轴补偿值"]
      pitch_offset: [
        "5.0 6.0 -1.0 0.4 0.0",
        "5.0 6.0  0.4 0.8 0.0",
        "5.0 6.0  0.8 1.2 0.0",
        "6.0 7.0 -1.0 0.4 0.0",
        "6.0 7.0  0.4 0.8 0.0",
        "6.0 7.0  0.8 1.2 0.0",
        "7.0 8.0 -1.0 0.4 0.0",
        "7.0 8.0  0.4 0.8 0.0",
        "7.0 8.0  0.8 1.2 0.0",
      ]

    #       ekf:
    #   sigma2_q_x: 10.0
    #   sigma2_q_y: 10.0

    #   sigma2_q_z: 1.0

    #   sigma2_q_yaw: 20.0
    #   sigma2_q_r: 80.0


    #  # r_x: 0.10288572347
    #   #r_y: 0.1064594022
    #   #r_z: 0.250901387
    #   #r_yaw: 0.0144229309

    #   r_x: 0.0846537194
    #   r_y: 0.1521677530
    #   r_z: 0.1083228776
    #   r_yaw: 0.1332647596
# R_x:0.0043715573
# R_y:0.0443530405
# R_z:0.0536129460
# R_yaw:0.1651087658
# s2qx:31.1798632047
# s2qy:20.8053758918
# s2qz:22.8736454857
# s2qyaw:57.8300360557
