camera:
  acquisition_frame_rate: 160
  adc_bit_depth: Bits_8
  camera_info_path: /home/nvidia/wust_vision/config/camera_info.yaml
  exposure_time: 3500
  gain: 10
  pixel_format: BayerRG8
  serial: ''
classify_label_path: /home/nvidia/wust_vision/model/label.txt
classify_model_path: /home/nvidia/wust_vision/model/lenet.onnx
control:
  alpha_pitch: 0.9
  alpha_yaw: 0.9
  control_rate: 1000
  device_name: /dev/ttyACM_stm
  max_pitch_change: 5
  max_yaw_change: 10
  use_serial: false
debug:
  debug_h: 480
  debug_mode: true
  debug_show_dt: 0.01
  debug_w: 640
detect_color: 1
light:
  binary_thres: 85
  expand_ratio_h: 1.1
  expand_ratio_w: 1.1
  max_angle: 40
  max_ratio: 0.45
  min_ratio: 0.02
logger:
  log_level: INFO
  log_path: /home/nvidia/wust_log
  use_logcli: true
  use_logfile: false
  use_simplelog: true
max_infer_running: 4
model:
  conf_threshold: 0.25
  input_h: 416
  input_w: 416
  nms_threshold: 0.3
  num_classes: 8
  num_colors: 4
  top_k: 128
model_path: /home/nvidia/wust_vision/model/opt-1208-001.onnx
solver:
  bullet_speed: 20
  compenstator_type: ideal
  controller_delay: 0
  gravity: 9.8
  iteration_times: 120
  max_tracking_v_yaw: 22
  pitch_offset:
  - d_max: 6
    d_min: 5
    h_max: 0.4
    h_min: -1
    pitch_off: 0
    yaw_off: 0
  - d_max: 6
    d_min: 5
    h_max: 0.8
    h_min: 0.4
    pitch_off: 0
    yaw_off: 0
  - d_max: 6
    d_min: 5
    h_max: 1.2
    h_min: 0.8
    pitch_off: 0
    yaw_off: 0
  - d_max: 7
    d_min: 6
    h_max: 0.4
    h_min: -1
    pitch_off: 0
    yaw_off: 0
  - d_max: 7
    d_min: 6
    h_max: 0.8
    h_min: 0.4
    pitch_off: 0
    yaw_off: 0
  - d_max: 7
    d_min: 6
    h_max: 1.2
    h_min: 0.8
    pitch_off: 0
    yaw_off: 0
  - d_max: 8
    d_min: 7
    h_max: 0.4
    h_min: -1
    pitch_off: 0
    yaw_off: 0
  - d_max: 8
    d_min: 7
    h_max: 0.8
    h_min: 0.4
    pitch_off: 0
    yaw_off: 0
  - d_max: 8
    d_min: 7
    h_max: 1.2
    h_min: 0.8
    pitch_off: 0
    yaw_off: 0
  prediction_delay: 0
  resistance: 0.092
  shooting_range_h: 0.12
  shooting_range_w: 0.12
  side_angle: 20
tf:
  gimbal2camera_pitch: 0
  gimbal2camera_roll: 0
  gimbal2camera_x: 0.07
  gimbal2camera_y: 0
  gimbal2camera_yaw: 180
  gimbal2camera_z: -0.05
  odom2gimbal_pitch: 0
  odom2gimbal_roll: 0
  odom2gimbal_yaw: 0
tracker:
  ekf:
    r_x: 0.0046302163
    r_y: 0.032246781
    r_yaw: 0.3651087658
    r_z: 0.265958766
    s2qd_zc: 800
    s2qr: 80
    s2qx: 10
    s2qy: 10
    s2qyaw: 20
    s2qz: 1
  jump_thresh: 0.4
  lost_time_thres: 0.1
  max_inconsistent_count: 3
  max_match_distance: 0.5
  max_match_yaw_diff: 0.7
  max_match_z_diff: 0.1
  min_valid_velocity_thresh: 0.01
  obs_vyaw_buffer_thres: 5
  obs_yaw_stationary_thresh: 1
  pred_yaw_stationary_thresh: 0.5
  rotation_inconsistent_cooldown_limit: 5
  target_frame: gimbal_odom
  tracking_thres: 5
use_calculation: false
