debug:
  debug_mode: true
  show_armor: true
  show_target: true

max_infer_running: 4

classify_model_path: "/home/hy/wust_vision/model/mlp.onnx"
classify_label_path: "/home/hy/wust_vision/model/label.txt"


model:
  model_path: "/home/hy/wust_vision/model/opt-1208-001.onnx"
  device_type: "GPU"  
  conf_threshold: 0.25
  top_k: 128
  nms_threshold: 0.3


light:
  expand_ratio_w: 1.1
  expand_ratio_h: 1.1
  binary_thres: 85
  min_ratio: 0.02
  max_ratio: 0.45
  max_angle: 40.0


camera:
  camera_info_path: "/home/hy/wust_vision/config/camera_info.yaml"
  serial: "" 
  acquisition_frame_rate: 160
  exposure_time: 3500
  gain: 16.0
  adc_bit_depth: "Bits_8"
  pixel_format: "BayerRG8"

detect_color: 0

tracker:
  target_frame: "odom"
  max_match_distance: 0.5
  max_match_yaw_diff: 1.0
  tracking_thres: 5
  lost_time_thres: 0.2
  ekf:
    s2qx: 0.1
    s2qy: 0.1
    s2qz: 0.2
    s2qyaw: 6.0
    s2qr: 80.0
    s2qd_zc: 1000.0
    r_x: 3e-3
    r_y: 3e-3
    r_z: 5e-3
    r_yaw: 5e-3
