use_calculation:  false
detect_color: 1

logger:
  log_level: "DEBUG"
  log_path: "/home/hy/wust_log"
  use_simplelog: false
  use_logfile: false
  use_logcli:  true

debug:
  debug_mode: true
  debug_w: 1440
  debug_h: 1080
  debug_show_dt: 0.05

max_infer_running: 4

classify_model_path: "/home/hy/wust_vision/model/lenet.onnx"
classify_label_path: "/home/hy/wust_vision/model/label.txt"


model:
  model_path: "/home/hy/wust_vision/model/opt-1208-001.onnx"
  device_type: "GPU"  
  conf_threshold: 0.7
  top_k: 128
  nms_threshold: 0.3


light:
  expand_ratio_w: 1.1
  expand_ratio_h: 1.1
  binary_thres: 85
  min_ratio: 0.02
  max_ratio: 0.45
  max_angle: 40.0



# camera:
#   trigger_mode: false
#   invert_image: false
#   camera_info_path: "/home/hy/wust_vision/config/camera_info.yaml"
#   exposure_time_us: 3500
#   gain: 10.0
camera:
  serial: ""
  camera_info_path: "/home/hy/wust_vision/config/camera_info.yaml"
  acquisition_frame_rate: 200
  exposure_time: 3500
  gain: 10.0
  adc_bit_depth: "Bits_8"
  pixel_format: "BayerRG8"


tf:
  gimbal2camera_x:  0.0
  gimbal2camera_y:  0.0
  gimbal2camera_z:  0.0
  gimbal2camera_roll: 1.0
  gimbal2camera_pitch: 6.0
  gimbal2camera_yaw: 180.0
  odom2gimbal_roll: 0.0
  odom2gimbal_pitch: 0.0
  odom2gimbal_yaw: 0.0


control:
  use_serial: false
  device_name: "/dev/ttyACM0"
  control_rate: 1000
  alpha_yaw: 0.9
  alpha_pitch: 0.9
  max_yaw_change: 10.0
  max_pitch_change: 5.0
  

tracker:
  target_frame: "odom"
  max_match_distance: 0.5
  max_match_yaw_diff: 0.5
  max_match_z_diff: 0.1
  tracking_thres: 5
  lost_time_thres: 0.2
  obs_vyaw_buffer_thres: 6
  obs_yaw_stationary_thresh: 0.7
  pred_yaw_stationary_thresh: 0.6
  min_valid_velocity_thresh: 0.01
  max_inconsistent_count: 2
  rotation_inconsistent_cooldown_limit: 5
  jump_thresh: 0.4
  ekf:
    s2qx: 10.0
    s2qy: 10.0
    s2qz: 1.0
    s2qyaw: 20.0
    s2qr: 80.0
    s2qd_zc: 800.0
    r_x: 0.0180952234
    r_y: 0.0214626785
    r_z: 0.0016992016
    r_yaw: 0.6092185450
solver:
      shooting_range_w: 0.12
      shooting_range_h: 0.12
      prediction_delay: 0.05
      controller_delay: 0.0
      max_tracking_v_yaw: 180.0 #转速(rad/s)大于这个值时瞄准机器人中心 
      side_angle: 20.0 
      bullet_speed: 25.0
      compenstator_type: "ideal"
      gravity: 9.8
      resistance: 0.092
      iteration_times: 20 # 补偿的迭代次数
      # ["距离下限, 距离上限, 高度下限, 高度下限, pitch轴补偿值, yaw轴补偿值"]
      pitch_offset: [
        "5.0 6.0 -1.0 0.4 0.0 0.0",
        "5.0 6.0  0.4 0.8 0.0 0.0",
        "5.0 6.0  0.8 1.2 0.0 0.0",
        "6.0 7.0 -1.0 0.4 0.0 0.0",
        "6.0 7.0  0.4 0.8 0.0 0.0",
        "6.0 7.0  0.8 1.2 0.0 0.0",
        "7.0 8.0 -1.0 0.4 0.0 0.0",
        "7.0 8.0  0.4 0.8 0.0 0.0",
        "7.0 8.0  0.8 1.2 0.0 0.0",
      ]

# R_x:0.0009817214
# R_y:0.0119015582
# R_z:0.0187810500
# R_yaw:0.1886811519

# R_x:0.0180952234
# R_y:0.0214626785
# R_z:0.0006992016
# R_yaw:0.6092185450