use_calculation: false

logger:
  log_level: "DEBUG"
  log_path: "/home/hy/wust_log"
  use_simplelog: false
  use_logfile: true
  use_logcli:  true

debug:
  debug_mode: true
  debug_w: 1440
  debug_h: 1080
  debug_show_dt: 0.01

max_infer_running: 4

classify_model_path: "/home/hy/wust_vision/model/lenet.onnx"
classify_label_path: "/home/hy/wust_vision/model/label.txt"

model_path: "/home/hy/wust_vision/model/opt-1208-001.onnx"
model:
  input_w: 416
  input_h: 416
  num_classes: 8
  num_colors: 4
  conf_threshold: 0.25
  nms_threshold: 0.3
  top_k: 128

light:
  expand_ratio_w: 1.1
  expand_ratio_h: 1.1
  binary_thres: 85
  min_ratio: 0.02
  max_ratio: 0.45
  max_angle: 40.0

camera:
  serial: ""
  camera_info_path: "/home/hy/wust_vision/config/camera_info.yaml"
  acquisition_frame_rate: 165
  exposure_time: 3500
  gain: 12.0
  adc_bit_depth: "Bits_8"
  pixel_format: "BayerRG8"

detect_color: 0

tf:
  gimbal2camera_x:  0.0
  gimbal2camera_y:  0.0
  gimbal2camera_z:  0.0
  gimbal2camera_roll: 0.0
  gimbal2camera_pitch: 0.0
  gimbal2camera_yaw: 0.0

tracker:
  target_frame: "odom"
  max_match_distance: 0.5
  max_match_yaw_diff: 0.7
  tracking_thres: 5
  lost_time_thres: 0.1
  obs_vyaw_buffer_thres: 5
  obs_yaw_stationary_thresh: 1.0
  pred_yaw_stationary_thresh: 0.5
  min_valid_velocity_thresh: 0.01
  max_inconsistent_count: 3
  rotation_inconsistent_cooldown_limit: 5
  ekf:
    s2qx: 7.0
    s2qy: 7.0
    s2qz: 1.0
    s2qyaw: 30.0
    s2qr: 50.0
    s2qd_zc: 800.0
    r_x: 0.0046302163
    r_y: 0.0322467810
    r_z: 0.2659587660
    r_yaw: 0.3651087658
solver:
      prediction_delay: 0.0
      controller_delay: 0.0
      max_tracking_v_yaw: 180.0 #转速(rad/s)大于这个值时瞄准机器人中心 
      side_angle: 20.0 
      bullet_speed: 25.0
      compenstator_type: "ideal"
      gravity: 9.8
      resistance: 0.092
      iteration_times: 120 # 补偿的迭代次数
      # ["距离下限, 距离上限, 高度下限, 高度下限, pitch轴补偿值"]
      pitch_offset: [
        "5.0 6.0 -1.0 0.4 0.0",
        "5.0 6.0  0.4 0.8 0.0",
        "5.0 6.0  0.8 1.2 0.0",
        "6.0 7.0 -1.0 0.4 0.0",
        "6.0 7.0  0.4 0.8 0.0",
        "6.0 7.0  0.8 1.2 0.0",
        "7.0 8.0 -1.0 0.4 0.0",
        "7.0 8.0  0.4 0.8 0.0",
        "7.0 8.0  0.8 1.2 0.0",
      ]


      
# R_x:0.0046302163
# R_y:0.0322467810
# R_z:0.0229685939
# R_yaw:0.2659587660
# s2qx:85.5507288784
# s2qy:79.1156214139
# s2qz:76.3573371065
# s2qyaw:90.5662286888
# R_x:0.0005405574
# R_y:0.0193988931
# R_z:0.0253446886
# R_yaw:0.1906375660